spring:
  application:
    name: dueldle-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/dueldle
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      jbdc:
        batch_size: 10
        order_inserts: true
        order_updates: true
      ddl-auto: update
    show-sql: true
